[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["export NVM_DIR=\"$HOME/.nvm\" && export PATH=\"/root/.local/share/pnpm:$PATH\" && npm install -g pnpm && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["export PATH=\"/root/.local/share/pnpm:$PATH\" && pnpm run build"]

[start]
cmd = "export PATH=\"/root/.local/share/pnpm:$PATH\" && pnpm run start"
